mongodb-host: localhost
mongodb-port: 27017
mongodb-database: melita

gateway-service-port: 5000

order-tracking-service-host: http://localhost
order-tracking-service-port: 5010

care-system-port: 5002

order-fullfilment-system-port: 5003

authorization-server-host: http://localhost
authorization-server-port: 5004

config-server-port: 5005
